<?php
    return [
        'term1' => 'Políticas de viaje',

        'term2' => '
        <h3>1. Our Aims</h3>
        <p>As a company we want to to make tourism sustainable for the long term. We are aware of the great impact (positive and negative) tourism can have. Our commitment is to operate according to these guidelines:</p>
        <ul style="list-style: none;">
          <li class="lmb">
            <h5>a. Care for the environment</h5>
            Pausa aims to limit our impact on the environment in several ways. Our partner, the NGO “Conservamos por Naturaleza” (We Preserve by Nature), helps us leading a strict selection process for our tour operators. We make sure each of our experiences follow strict rules that minimise the effects of our presence in the area so we can preserve and protect delicate ecosystems, wildlife and natural habitats.
          </li>
          <li class="lmb">
            <h5>b. Make a difference</h5>
            Pausa supports many different community-led projects around the country, with the goal of ensuring that the most of the money generated by your travelling goes directly to those communities, in order to make a lasting difference.
          </li>
          <li class="lmb">
            <h5>c. Support the local economy</h5>
            We ensure that local economies benefit from our business by promoting that our tour operators use locally-owned accommodation, employ local people as specialist guides, work with local operators and suppliers and source food from locally-owned stores. In doing so, we are not only trusting in local communities but also offering travelers a genuine insight into a region and its people. We don’t have abusively long payment periods to our operators, we make sure that the minute our travelers pay us, we transfer more than 80% of the income to the local community. Our communities and families trust us and perceive us as an important ally to reach to new markets they couldn’t have reached on their own because they are too focused on the operation of their experience and they don’t have the digital, commercial and logistic expertise.
          </li>
          <li class="lmb">
            <h5>d. Reduce carbon emissions</h5>
            We ensure that our experiences have a minimal impact on the environment by assuring that our operators design tours that enable people to travel on the most suitable transport to the region. Your tours may take you on: busses, boats, trains, trams, tuk-tuks or other locally hired transport to offer you an authentic travel experience in the region.
          </li>
          <li class="lmb">
            <h5>e. Promote animal welfare</h5>
            Many of our tours include opportunities to view local wildlife in national parks or at private conservation areas. Whilst these excursions can benefit both the animals and the local people who depend on them for a living, they need to adhere to strict animal welfare standards to ensure that the animals aren`t exploited. View our designated Animal Welfare Policy bellow.
          </li>
          <li class="lmb">
            <h5>f. On-tour Practices</h5>
            The standard of accommodation and services can vary when visiting different regions and destinations. Pausa chooses those which are safe, enjoyable and locally operated, in a sustainable way. We have experiences that involve camping, staying in bungalows or even in luxury ecolodges.
            <br />
            Local resources such as water and electricity are often in short supply and tourism can put pressure on these services and supplies which can in turn reduce the supplies available to local people. To help reduce this impact, Pausa staff will inform you about local issues such as the scarcity of water in a particular area and give you tips about how to reduce use and wastage.
            <br />
            We will also inform you about the availability of hot water and the limitations of local plumbing, such as the squat vs western-style toilets and what`s flushable. The sewer systems in many destinations are not able to cope with non-human waste. Blockages can cause floods which deprive local people of their vital services.<br />
            <br />
            Pausa clients may be asked by tour leaders and crew to:
            <ul>
              <li>
                Appliances should be turned off and plugs pulled out of sockets rather than left on standby, which uses electricity
              </li>
              <li>
              Consider taking a short shower once daily rather than a bath
              </li>
              <li>
              Turn the tap off while brushing teeth or shaving and put a plug in the basin at other times to reduce water use and wastage
              </li>
              <li>
              Reconsider whether they need new towels every day and let the accomodation know if they would prefer to reuse their towels – this would reduce water used and reduce the amount of detergents in the waste water which ends up in the sewer system / waterways / ocean
              </li>
              <li>
              Recycle cans, paper and plastics if facilities exist at the accommodation
              </li>
              <li>
              Pausa would encourage travellers to hold on to their plastics if possible to recycle elsewhere if such facilities aren’t available at the hotel
              </li>
            </ul>
          </li>
        </ul>

        <h3>2. Animal Welfare</h3>
        <p>
        We promote the welfare of animals in the following ways:
        </p>
        <h5>Offering Wildlife encounters that directly benefit those species</h5>
        <p>
        Many of our tours include excursions where travelers can observe or interact with wildlife, either in national parks that offer areas where the animals are protected from poaching or hunting, or at private conservation areas that aim to protect and rehabilitate endangered animals and flora.
        </p>
        <h5>Guidelines for visiting pristine areas and interacting with wildlife</h5>
        <p>
        Travel to national parks and wildlife areas can bring positive economic benefits as entrance fees contribute to the maintenance and conservation of local flora and animal species, while visitors benefit from the educational aspects of the area and take away with them an increased awareness of the need and place for conservation. Pausa’s operators are expected to adhere to the following guidelines and will instruct you to do the same when visiting areas with delicate natural environments and when interacting with wildlife, whether at national parks or reserves.
        </p>
        <ul>
          <li>
            Follow National parks and reserves regulations as well as the instructions of their staff regarding appropriate conduct
          </li>
          <li>
          Stick to roads and established paths
          </li>
          <li>
          Follow the instructions of local guides regarding appropriate conduct
          </li>
          <li>
          Maintain the recommended distance from animals, as instructed by your local expert guide
          </li>
          <li>
          Do not feed the animals – this can make animals sick, overweight, and be stressful for them
          </li>
          <li>
          Do not touch the animals – this can transmit diseases to the animals and you may also put yourself at risk of transmission at the same time
          </li>
          <li>
          Approach animals quietly, cautiously and slowly so as to avoid distressing them, but avoid approaching nesting or breeding sites as this can cause stress to parents and young alike. If the animal’s behaviour changes as you approach, you’re probably too close
          </li>
          <li>
          Consider getting a camera with a long-range lens so you can take candid shots of the animal’s natural behaviour
          </li>
          <li>
          Turn off your flash when taking photographs and avoid shining lights directly at animals or in their eyes at night
          </li>
          <li>
          Do not support attractions which use animals as entertainment for profit. These animals are often taken from the wild, mistreated and are trained to perform unnatural behaviours which are often harmful to the animal
          </li>
          <li>
          Avoid purchasing anything made of exotic wild animal product such as fur, bone or insect specimens. Often this trade is illegal and the animal may have suffered during the process
          </li>
          <li>
          Avoid wild animal meat on restaurant menus, even if it does sound adventurous. It is usually illegal to import these items into your home country and this practice encourages poaching, which can have devastating impacts on local animal populations.
          </li>
        </ul>

        <h5>Guidelines for visiting historic sites</h5>
        <p>
        Some of our tours may offer opportunities to visit ancient places where our entrance fees contribute to the maintenance and restoration of these unique places. Pausa asks that travellers respect signage, take only photographs and leave no litter or graffiti behind, even if others have done so. Do not attempt to bring home any rocks or stones or other souvenirs of the location and don`t purchase such items from vendors as this can encourage the ongoing destruction of local areas of interest.
        </p>
        <h5>Guidelines for camping and campfires</h5>
        <p>
        Some of our tours may involve camping. Pausa’s operators are expected to encourage clients to adhere to the following guidelines when camping:
        </p>
        <p>
        At popular areas:
        </p>
        <ul>
          <li>
          Use existing camping sites
          </li>
          <li>
          Keep campsites small and focus activity on previously cleared areas
          </li>
          <li>
          Do not disturb vegetation
          </li>
          <li>
          Do not urinate near or into streams or dump chemicals into the water – use the toilet and ablution facilities provided
          </li>
          <li>
          Avoid using soaps with phosphates and don’t wash while you’re swimming if the fresh waterway is likely to be polluted for local people downstream
          </li>
          <li>
          Be considerate of other campers and keep the noise down at night-time
          </li>
          <li>
          Be considerate when lighting a campfire. Is it an appropriate and safe area? Are the fuels used to light the fire from a renewable resource? Will it be possible put out the fire afterwards and ensure it does not leave any blemishes on the local landscape?
          </li>
        </ul>

        <h3>3. In Our Operation</h3>
        <p>
        Pausa recognises that it is not only on-location staff who have environmental responsibilities but also our administration staff in our office. Pausa believes in leading through example and operates in this manner to encourage other businesses and individuals we’re in contact with to be considerate of the environment.
        </p>
        <h5>a. Land and office space</h5>
        <p>
        Pausa avoids leasing office space. We keep our operation digital and use exclusively co-working spaces for special meetings.
        </p>
        <h5>b. Paper</h5>
        <ul>
          <li>
          Pausa does not print annual brochures or tour catalogues and the limited amount of paper based promotional materials are made using paper from renewable sources
          </li>
          <li>
          Pausa stores all data electronically rather than on paper printouts
          </li>
          <li>
          Clients and agents can only book online – paper booking forms are not required
          </li>
          <li>
          All tour dossiers and other pre-departure information is emailed to clients, which reduces paper usage
          </li>
          <li>
          We do not print documents or emails unnecessarily
          </li>
          <li>
          Where photocopying is necessary we try to print on both sides of the page
          </li>
        </ul>
        <h5>c. Staff Education</h5>
        <p>
        The Pausa Responsible Travel policy is included in induction materials for new staff
        </p>
        <p>
        All staff are made aware of the reason for recycling and are asked to recycle all waste paper, cardboard, cans and plastics
        </p>
        <p>
        Staff are reminded to turn off computers and appliances, air conditioning/heating and lights at night
        </p>

        <h3>4. Supporting Local Economies</h3>
        <p>
        When we`re looking for new operators we are very careful to ensure that our tours will provide maximum opportunities to engage with the local people and natural environment, so that local economies benefit directly from our business and our travellers gain a genuine insight into region and its people.
        </p>
        <h5>Building relationships with local operators and suppliers</h5>
        <p>
        We have built long standing and successful relationships with operators all over the country. Our continuing success as a business lies in our support of local communities who have made us welcome. Our commitment to supporting local businesses means that these operators continue to prosper and empowers local people, leading to increased confidence and development of their products and services.
        </p>
        <h5>Local excursions and adventure activities</h5>
        <p>
        Optional excursions are often an exciting part of a journey with Pausa. We look for activities which will suit our clients varied tastes and budgets, while supporting local operators and putting money back into local economies.
        </p>
        <h5>Consultation with locals</h5>
        <p>
        Pausa is highly selective of local associates or operators and aims to approach only those who share its positive and long-term developmental outlook. Pausa is committed to being honest about the impacts our products may have on local lifestyles and communities. We ensure they are happy to have our products in their areas and do not impose developments if they are unwanted.
        </p>
        <h5>Local guides and local representatives</h5>
        <p>
        Pausa promotes that our operators use local people, representatives and specialist guides. This ensures knowledgeable, enthusiastic operators, thorough guiding and support of local individuals and businesses. Pausa will endeavour to ensure that local partners are employed under fair conditions, are paid a living wage for reasonable hours and are given adequate support by our operators.
        </p>
        <p>
        Our close relationships with local operators allow us to put more money back into the local economies. It also allows clients to gain greater insight into the local customs and traditions through their contact with our local operators. On certain tours the specialist knowledge of guides is invaluable.
        </p>
        <h5>Local accommodation</h5>
        <p>
        At Pausa we feel that travelling to different regions provides a chance to experience new cultures and interact with new people. It is not an opportunity for travelers to impose their culture upon others. We encourage clients to be sensitive to the host culture through preserving and encouraging cultural and social diversity. We discourage the display of traditional or cultural "shows" for commercial purposes. As enjoyable as they can be for clients, we are attempting to keep local culture and tradition genuine rather than encouraging it to be used as a commercial attraction. That`s why there`s the opportunity to tay with small family owned hotels and hostels. We support  local businesses and encourage the further development of such businesses.
        </p>
        ',
    ]
?>
